'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Test

    Partial Public Class Customer
        Public Property ID As Integer
        Public Property FirstName As String
        Public Property LastName As String
        Public Property Company As String
        Public Property Address As String
        Public Property City As String
        Public Property Country As String
        Public Property ZipCode As Integer
    
    End Class

End Namespace
