'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Test

    Partial Public Class AliEntities1
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=AliEntities1")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Customers() As DbSet(Of Customer)
        Public Overridable Property Logs() As DbSet(Of Login)

    End Class

End Namespace
